// 手話ミラー - 学習データ
//
// 各手話は「見本（説明文・絵文字）」と「ARで照合するための手形(handshape)」を持つ。
// handshape は [親指, 人さし指, 中指, 薬指, 小指] の配列で、
//   1 = その指を立てる（伸ばす）
//   0 = その指を曲げる（握る）
//   null = どちらでもよい（判定しない）
// MediaPipe で検出した手から同じ形式のベクトルを作り、一致度を計算する。

export const FINGER_NAMES = ['親指', '人さし指', '中指', '薬指', '小指'];

// 段階的に学ぶステージ。画像の分類に対応。
export const STAGES = [
  { id: 'greet',   title: 'あいさつ',       icon: '👋', color: '#ff6b6b', desc: '毎日つかう基本のあいさつ' },
  { id: 'self',    title: '自己紹介',       icon: '🙋', color: '#4dabf7', desc: '自分のことを伝える言葉' },
  { id: 'verb',    title: 'よく使う言葉',   icon: '🗣️', color: '#51cf66', desc: '日常の動作をあらわす言葉' },
  { id: 'feel',    title: '気持ち・様子',   icon: '😊', color: '#fcc419', desc: '感情や状態をつたえる言葉' },
  { id: 'number',  title: '数字（1〜10）',  icon: '🔢', color: '#9775fa', desc: '指であらわす数の表現' },
  { id: 'finger',  title: '指文字',         icon: '✋', color: '#22b8cf', desc: '五十音を手で表す基礎' },
];

// 手話データ本体
export const SIGNS = [
  // ── あいさつ ──────────────────────────────
  { id: 'ohayou', stage: 'greet', word: 'おはよう', reading: 'おはよう', emoji: '🌅',
    handshape: [0, 0, 0, 0, 0],
    description: '握りこぶしをこめかみあたりにあて、その手を前にずらす。',
    motion: 'こめかみ → 前方へ',
    tip: '朝、目が覚めて枕から頭を上げるイメージ。',
    example: '朝の最初のあいさつに。「おはよう！」' },
  { id: 'konnichiwa', stage: 'greet', word: 'こんにちは', reading: 'こんにちは', emoji: '☀️',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指をそろえて立て、おでこにあてて前に出す。',
    motion: 'おでこ → 前方へ',
    tip: '太陽が高くのぼる昼を表す動き。',
    example: '昼間の出会いに。「こんにちは」' },
  { id: 'konbanwa', stage: 'greet', word: 'こんばんは', reading: 'こんばんは', emoji: '🌙',
    handshape: [0, 1, 1, 0, 0],
    description: '両手の人さし指と中指を立て、顔の前で重ねるように合わせる。',
    motion: '顔の前で交差',
    tip: '夜のとばりが下りる様子をあらわす。',
    example: '夜のあいさつに。「こんばんは」' },
  { id: 'arigatou', stage: 'greet', word: 'ありがとう', reading: 'ありがとう', emoji: '🙏',
    handshape: [1, 1, 1, 1, 1],
    description: '胸にあてた右手（手のひら下向き）を、上にスッと持ち上げる。',
    motion: '胸 → 上へ',
    tip: '相手への感謝を持ち上げるように。',
    example: '感謝をつたえるときに。「ありがとう」' },
  { id: 'gomen', stage: 'greet', word: 'ごめんなさい', reading: 'ごめんなさい', emoji: '🙇',
    handshape: [0, 0, 0, 0, 0],
    description: '握った右手の人さし指側を額にあて、軽く頭を下げる。',
    motion: '額にあてて会釈',
    tip: '反省の気持ちをこめて。',
    example: '謝るときに。「ごめんなさい」' },
  { id: 'sayonara', stage: 'greet', word: 'さようなら', reading: 'さようなら', emoji: '👋',
    handshape: [1, 1, 1, 1, 1],
    description: '開いた手を立て、左右に軽くふる。',
    motion: '左右にふる',
    tip: '別れぎわのあいさつ。手をふるだけでも伝わる。',
    example: '別れのときに。「さようなら」' },

  // ── 自己紹介 ──────────────────────────────
  { id: 'watashi', stage: 'self', word: 'わたし・私', reading: 'わたし', emoji: '👤',
    handshape: [1, 0, 0, 0, 0],
    description: '親指または人さし指で自分の胸（鼻）を指す。',
    motion: '自分を指す',
    tip: '一人称はすべてこの動きが基本。',
    example: '「わたしは〜です」の主語に。' },
  { id: 'namae', stage: 'self', word: '名前', reading: 'なまえ', emoji: '📛',
    handshape: [1, 0, 0, 0, 0],
    description: '親指を立て、胸の前に判子を押すようにポンとあてる。',
    motion: '胸の前に押す',
    tip: '名前＝判子のイメージ。',
    example: '「名前はなんですか？」' },
  { id: 'onegai', stage: 'self', word: 'よろしくお願いします', reading: 'おねがい', emoji: '🤝',
    handshape: [1, 0, 0, 0, 0],
    description: '右手の親指を立て、左手の甲にのせて軽く前に倒し、頭を下げる。',
    motion: 'のせて会釈',
    tip: 'あいさつの締めくくりに使う定番。',
    example: '自己紹介の最後に。「よろしくお願いします」' },
  { id: 'hai', stage: 'self', word: 'はい', reading: 'はい', emoji: '⭕',
    handshape: [0, 0, 0, 0, 0],
    description: '握ったこぶしを、うなずくように1回スッと下げる。',
    motion: '上 → 下へ（うなずき）',
    tip: '首のうなずきと合わせると伝わりやすい。',
    example: '肯定の返事に。「はい」' },
  { id: 'iie', stage: 'self', word: 'いいえ', reading: 'いいえ', emoji: '❌',
    handshape: [0, 1, 0, 0, 0],
    description: '人さし指を立て、左右に小さくふる。',
    motion: '左右にふる',
    tip: '「ちがう」「ない」にも使える。',
    example: '否定の返事に。「いいえ」' },
  { id: 'wakaranai', stage: 'self', word: 'わかりません', reading: 'わかりません', emoji: '🤷',
    handshape: [1, 1, 1, 1, 1],
    description: '胸にあてた手を、払うように横へ動かす。',
    motion: '胸 → 横へ払う',
    tip: '「わかる」は胸を上下、「わからない」は払う動き。',
    example: '「わかりません」と伝えるときに。' },

  // ── よく使う言葉 ──────────────────────────
  { id: 'taberu', stage: 'verb', word: '食べる', reading: 'たべる', emoji: '🍚',
    handshape: [1, 1, 1, 0, 0],
    description: '指先をそろえ、口元へ運んで食べるまねをする。',
    motion: '口元へ運ぶ',
    tip: 'お箸やスプーンを口に運ぶイメージ。',
    example: '「ごはんを食べる」' },
  { id: 'nomu', stage: 'verb', word: '飲む', reading: 'のむ', emoji: '🥤',
    handshape: [1, 1, 1, 1, 1],
    description: 'コップを持つ手の形をつくり、口元へかたむける。',
    motion: '口元へかたむける',
    tip: 'コップで飲むしぐさそのまま。',
    example: '「水を飲む」' },
  { id: 'miru', stage: 'verb', word: '見る', reading: 'みる', emoji: '👀',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指を目に向けてから、見る方向へ向ける。',
    motion: '目 → 対象へ',
    tip: '視線が飛んでいくイメージ。',
    example: '「テレビを見る」' },
  { id: 'kiku', stage: 'verb', word: '聞く', reading: 'きく', emoji: '👂',
    handshape: [1, 0, 0, 0, 1],
    description: '手のひら（または親指と小指）を耳にあてる。',
    motion: '耳にあてる',
    tip: '音を耳に集めるイメージ。',
    example: '「音楽を聞く」' },
  { id: 'iku', stage: 'verb', word: '行く', reading: 'いく', emoji: '🚶',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指をそろえて立て、前方へ進める。',
    motion: '自分 → 前方へ',
    tip: '自分から離れていく方向。',
    example: '「学校へ行く」' },
  { id: 'kuru', stage: 'verb', word: '来る', reading: 'くる', emoji: '🙌',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指をそろえ、自分の方へ引き寄せる。',
    motion: '前方 → 自分へ',
    tip: '「行く」の逆の動き。',
    example: '「友だちが来る」' },

  // ── 気持ち・様子 ──────────────────────────
  { id: 'ureshii', stage: 'feel', word: 'うれしい', reading: 'うれしい', emoji: '😄',
    handshape: [1, 1, 1, 1, 1],
    description: '両手の手のひらを胸にあて、上下にさする。',
    motion: '胸を上下にさする',
    tip: '心がはずむ様子。笑顔も大切。',
    example: '「会えてうれしい」' },
  { id: 'tanoshii', stage: 'feel', word: '楽しい', reading: 'たのしい', emoji: '🎉',
    handshape: [1, 1, 1, 1, 1],
    description: '両手を胸にあて、交互に上下へ大きく動かす。',
    motion: '胸を交互に上下',
    tip: 'わくわくが大きいほど動きも大きく。',
    example: '「とても楽しい！」' },
  { id: 'kanashii', stage: 'feel', word: '悲しい', reading: 'かなしい', emoji: '😢',
    handshape: [1, 1, 1, 1, 1],
    description: '両手を顔の前で下へ、涙が流れるように下ろす。',
    motion: '顔 → 下へ',
    tip: '涙が頬をつたう様子。',
    example: '「とても悲しい」' },
  { id: 'tsukareta', stage: 'feel', word: '疲れた', reading: 'つかれた', emoji: '😮‍💨',
    handshape: [1, 1, 1, 1, 1],
    description: '両手を肩にあて、力が抜けるように下げる。',
    motion: '肩 → 力を抜く',
    tip: '肩の力がストンと落ちる感じ。',
    example: '「今日は疲れた」' },
  { id: 'daijoubu', stage: 'feel', word: '大丈夫', reading: 'だいじょうぶ', emoji: '👌',
    handshape: [0, 0, 0, 1, 1],
    description: '親指と人さし指で輪（OK）をつくり、胸の前で軽く下げる。',
    motion: '胸の前で示す',
    tip: '安心・問題なしを表す。',
    example: '「心配ない、大丈夫」' },
  { id: 'sugoi', stage: 'feel', word: 'すごい', reading: 'すごい', emoji: '🤩',
    handshape: [1, 1, 1, 1, 1],
    description: '両手をパッと開いて前に出し、感嘆をあらわす。',
    motion: '両手を開いて前へ',
    tip: '驚きや称賛をこめて。',
    example: '「それはすごい！」' },

  // ── 数字（1〜10） ────────────────────────
  { id: 'num1', stage: 'number', word: '1', reading: 'いち', emoji: '☝️',
    handshape: [0, 1, 0, 0, 0],
    description: '人さし指を1本立てる。', motion: '静止', tip: '数えるときの基本。', example: '「1つください」' },
  { id: 'num2', stage: 'number', word: '2', reading: 'に', emoji: '✌️',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指を立てる。', motion: '静止', tip: 'ピースの形。', example: '「2人です」' },
  { id: 'num3', stage: 'number', word: '3', reading: 'さん', emoji: '🤟',
    handshape: [0, 1, 1, 1, 0],
    description: '人さし指・中指・薬指の3本を立てる。', motion: '静止', tip: '指3本でわかりやすく。', example: '「3時に会おう」' },
  { id: 'num4', stage: 'number', word: '4', reading: 'よん', emoji: '🖐️',
    handshape: [0, 1, 1, 1, 1],
    description: '親指以外の4本を立てる。', motion: '静止', tip: '親指だけ折る。', example: '「4個ある」' },
  { id: 'num5', stage: 'number', word: '5', reading: 'ご', emoji: '✋',
    handshape: [1, 1, 1, 1, 1],
    description: '5本すべての指を開く。', motion: '静止', tip: '手をパッと開く。', example: '「5分待って」' },
  { id: 'num6', stage: 'number', word: '6', reading: 'ろく', emoji: '👍',
    handshape: [1, 0, 0, 0, 0],
    description: '親指だけを立てる（5＋1の意味）。', motion: '静止', tip: '地域差あり。代表例。', example: '「6番です」' },
  { id: 'num7', stage: 'number', word: '7', reading: 'なな', emoji: '🤙',
    handshape: [1, 1, 0, 0, 0],
    description: '親指と人さし指を立てる。', motion: '静止', tip: '5＋2のイメージ。', example: '「7時集合」' },
  { id: 'num8', stage: 'number', word: '8', reading: 'はち', emoji: '🖖',
    handshape: [1, 1, 1, 0, 0],
    description: '親指・人さし指・中指を立てる。', motion: '静止', tip: '5＋3のイメージ。', example: '「8個入り」' },
  { id: 'num9', stage: 'number', word: '9', reading: 'きゅう', emoji: '🖐️',
    handshape: [1, 1, 1, 1, 0],
    description: '親指から薬指までの4本を立てる。', motion: '静止', tip: '5＋4のイメージ。', example: '「9月です」' },
  { id: 'num10', stage: 'number', word: '10', reading: 'じゅう', emoji: '👊',
    handshape: [0, 0, 0, 0, 0],
    description: 'こぶしを握って前に出す（または両手で示す）。', motion: '静止', tip: '地域差あり。代表例。', example: '「10人います」' },

  // ── 指文字（あ行＋一部） ──────────────────
  { id: 'fa', stage: 'finger', word: 'あ', reading: 'あ', emoji: '🤛',
    handshape: [1, 0, 0, 0, 0],
    description: 'グーを作り、親指を横に出す。', motion: '静止', tip: 'カタカナの「ア」の左払い。', example: '指文字「あ」' },
  { id: 'fi', stage: 'finger', word: 'い', reading: 'い', emoji: '🤙',
    handshape: [0, 0, 0, 0, 1],
    description: '小指を1本立てる。', motion: '静止', tip: 'カタカナの「イ」。', example: '指文字「い」' },
  { id: 'fu', stage: 'finger', word: 'う', reading: 'う', emoji: '✌️',
    handshape: [0, 1, 1, 0, 0],
    description: '人さし指と中指を立てる（下向き）。', motion: '静止', tip: 'カタカナの「ウ」。', example: '指文字「う」' },
  { id: 'fe', stage: 'finger', word: 'え', reading: 'え', emoji: '☝️',
    handshape: [0, 1, 1, 1, 1],
    description: '親指を折り、4本の指を立てて少し曲げる。', motion: '静止', tip: 'カタカナの「エ」。', example: '指文字「え」' },
  { id: 'fo', stage: 'finger', word: 'お', reading: 'お', emoji: '👌',
    handshape: [0, 0, 0, 1, 1],
    description: '親指と人さし指で輪を作り、残りを立てる。', motion: '静止', tip: 'カタカナの「オ」。', example: '指文字「お」' },
  { id: 'fka', stage: 'finger', word: 'か', reading: 'か', emoji: '✋',
    handshape: [1, 1, 1, 1, 1],
    description: '5本を開き、手を斜めにかまえる。', motion: '静止', tip: 'カタカナの「カ」。', example: '指文字「か」' },
];

// 会話シミュレーション用シナリオ。
// 各ターンは partner（相手の手話＝見本）と choice（自分が選ぶ）で構成。
export const SCENARIOS = [
  {
    id: 'first-meet', title: 'はじめまして', icon: '🤝', level: 1,
    intro: '初対面の人にあいさつし、自己紹介をしてみよう。',
    turns: [
      { partner: 'konnichiwa', text: '相手が「こんにちは」とあいさつしました。なんと返す？',
        choices: ['konnichiwa', 'sayonara', 'taberu'], answer: 'konnichiwa' },
      { partner: 'namae', text: '相手が「名前は？」とたずねました。まず何を表す？',
        choices: ['watashi', 'iku', 'kanashii'], answer: 'watashi' },
      { partner: 'onegai', text: '自己紹介の締めくくり。最後に伝える言葉は？',
        choices: ['onegai', 'gomen', 'num5'], answer: 'onegai' },
    ],
  },
  {
    id: 'cafe', title: 'カフェで注文', icon: '☕', level: 2,
    intro: 'お店で飲み物を注文する場面。数字も使ってみよう。',
    turns: [
      { partner: 'nomu', text: '店員が「お飲み物は？」と聞いています。「飲む」を表そう。',
        choices: ['nomu', 'miru', 'tsukareta'], answer: 'nomu' },
      { partner: 'num2', text: '「いくつ？」と聞かれました。「2つ」を表そう。',
        choices: ['num2', 'num5', 'num9'], answer: 'num2' },
      { partner: 'arigatou', text: '受け取ったら最後に伝えたい言葉は？',
        choices: ['arigatou', 'iie', 'kanashii'], answer: 'arigatou' },
    ],
  },
  {
    id: 'feelings', title: '気持ちを伝える', icon: '💬', level: 3,
    intro: '友だちと近況を話す場面。気持ちの手話を使おう。',
    turns: [
      { partner: 'konnichiwa', text: '友だちに会いました。まずあいさつ。',
        choices: ['konnichiwa', 'gomen', 'kiku'], answer: 'konnichiwa' },
      { partner: 'tanoshii', text: '「最近どう？」と聞かれて、楽しいと伝えたい。',
        choices: ['tanoshii', 'kanashii', 'iie'], answer: 'tanoshii' },
      { partner: 'sayonara', text: '別れぎわ。最後のあいさつは？',
        choices: ['sayonara', 'hai', 'num1'], answer: 'sayonara' },
    ],
  },
];

// ヘルパー
export const signById = id => SIGNS.find(s => s.id === id);
export const signsByStage = stage => SIGNS.filter(s => s.stage === stage);
export const stageById = id => STAGES.find(s => s.id === id);
export const scenarioById = id => SCENARIOS.find(s => s.id === id);
